name: test
on:
  push:
  pull_request:
  schedule:
    - cron: "0 8 1 * *"

jobs:
  test:
    name: test ${{ matrix.py }} - ${{ matrix.netapi }} - ${{ matrix.salt }}
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        py:
          - "3.9"
          - "3.10"
          - "3.11"
        netapi:
          - "cherrypy"
        salt:
          - "v3006.3"
          - "master"
    steps:
      - name: Setup python for test ${{ matrix.py }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.py }}
      - uses: actions/checkout@v4
      - name: Install setuptools_scm
        run: python -m pip install setuptools_scm
      - name: Install tox
        run: python -m pip install tox
      - name: Setup tests
        run: tox --notest -e py${{ matrix.py }}-${{ matrix.netapi }}-${{ matrix.salt }}
      - name: Run tests
        run: tox -e py${{ matrix.py }}-${{ matrix.netapi }}-${{ matrix.salt }}
